<a href="https://colab.research.google.com/github/SantiData87/yFinance/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importar librerias - Clase
import pandas as pd
import numpy as np
#Montar en drive
from google.colab import drive
import os
drive.mount('/content/drive')
%cd '/content/drive/MyDrive/- DATA/DATA SCIENCE/Data Sets/'
%ls

Mounted at /content/drive
/content/drive/MyDrive/- DATA/DATA SCIENCE/Data Sets
 aary.sqlite                             hist.html                  'nba.sqlite('
 bank-full.csv                          'Housing Market USA.csv'     NEE.csv
 BTC-Hourly.csv                          housing_test.csv            nyc-rolling-sales.csv
'CODER Clases DataSets - Copias'/        housing_train.csv          'pokemon_data (1).txt'
'Copia de winequality-red.csv'           HRDataset_v14.csv           pokemon_data.txt
 D.csv                                   IBM.csv                     SO.csv
'DUK (1).csv'                            locales-en-venta-2020.csv   SUELDOSPY.xlsx
 DUK.csv                                 Mercado_Pago.csv           'Time Series Data.csv'
 EXC.csv                                 nba_salary                 'unemployment analysis.csv'
 FED_rates.csv                           nba_salary.sqlite          'us_presidents 2.csv'
'Grafico de Frecuencia de Precios.jpg'   nba.sqlite                  winequality-red.csv

In [ ]:
#CSV - Drive
path='/content/drive/MyDrive/- DATA/DATA SCIENCE/Data Sets/titanic.csv'
df = pd.read_csv(path)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# .isin()

In [ ]:
df4 =df[df['Pclass'].isin([1,2])]
df4.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [ ]:
df4b =df[(df['Pclass'] == 1) | (df['Pclass'] == 2)]
df4b.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

# .loc

In [ ]:
df.loc[:,['Name', 'Sex']]

                                                  Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

In [ ]:
df.iloc[:,3:5]

                                                  Name     Sex
0                              Braund, Mr. Owen Harris    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                               Heikkinen, Miss. Laina  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                             Allen, Mr. William Henry    male
..                                                 ...     ...
886                              Montvila, Rev. Juozas    male
887                       Graham, Miss. Margaret Edith  female
888           Johnston, Miss. Catherine Helen "Carrie"  female
889                              Behr, Mr. Karl Howell    male
890                                Dooley, Mr. Patrick    male

[891 rows x 2 columns]

# Crear Columna

In [ ]:
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [ ]:
df['Fare']*1050

0       7612.500
1      74847.465
2       8321.250
3      55755.000
4       8452.500
         ...
886    13650.000
887    31500.000
888    24622.500
889    31500.000
890     8137.500
Name: Fare, Length: 891, dtype: float64

In [ ]:
df['Fare_Pesos'] = df['Fare']*1050

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Pesos
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,7612.500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,74847.465
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,8321.250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,55755.000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8452.500

## def

In [ ]:
def pay_if_reach(x):
  if x['Pclass'] == 1:
    return x['Fare'] * 1.2
  else:
    return x['Fare']

In [ ]:
df['Fare_for_reach'] = df.apply(pay_if_reach, axis=1)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Pesos,Fare_for_reach
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,7612.500,7.25000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,74847.465,85.53996
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,8321.250,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,55755.000,63.72000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8452.500,8.05000

## lambda
Son funciones anonimas porque no tienene nombre.
Sirve cuando aplico una funcion ua sola vez y no voy a necesitarla despues
La funcion solo vive en la linea de codigo utlizada y no puede ser "llamada" de nuevo

In [ ]:
df['Fare_for_reach_2'] = df.apply(lambda x: x['Fare'] * 1.2 if x['Pclass'] == 1 else x['Fare'] , axis=1)

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Pesos,Fare_for_reach,Fare_for_reach_2
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,7612.500,7.25000,7.25000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,74847.465,85.53996,85.53996
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,8321.250,7.92500,7.92500
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,55755.000,63.72000,63.72000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8452.500,8.05000,8.05000

# Merge
Es lo mismo que JOIN en SQL

In [ ]:
# Creao un DataFrame
df_class = pd.DataFrame({'Pclass': [1,2,3], 'Clase' : ['Alta', 'Media', 'Baja']})
df_class

   Pclass  Clase
0       1   Alta
1       2  Media
2       3   Baja

In [ ]:
# Left significa que tra TODOS los registros de 'df' y solo los de 'df_class? en donde coincide la columna 'Pclass'
df_merge = df.merge(df_class, how='left', on='Pclass')
df_merge

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Pesos,Fare_for_reach,Fare_for_reach_2,Clase
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,7612.500,7.25000,7.25000,Baja
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,74847.465,85.53996,85.53996,Alta
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,8321.250,7.92500,7.92500,Baja
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,55755.000,63.72000,63.72000,Alta
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,8452.500,8.05000,8.05000,Baja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,13650.000,13.00000,13.00000,Media
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,31500.000,36.00000,36.00000,Alta
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,24622.500,23.45000,23.45000,Baja
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,31500.000,36.00000,36.00000,Alta
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,8137.500,7.75000,7.75000,Baja